### ISSUE TITLE
Commandline Usage

### ISSUE THREAD

**Issue by salicodes** [tombensve/MarkdownDoc#25]
I will like to compile my markdown files to html and pdf using the commandline tool. But I don't understand the full commands and which argurment to pass where. I tried what I could and got this error message:
![Screenshot from 2019-06-07 17-39-54](https://user-images.githubusercontent.com/36715851/59119704-56017780-894b-11e9-98a5-ec49c2b1dcb3.png)

The command I am using is `java -jar markdowndoc-cmd-line-2.1.0.exec.jar pdf chapters/.*\.md --markdown`

**Comment by tombensve** [comment]
Here is an example of a commandline generation of PDF:

`java -jar markdowndoc-cmd-line-2.2.0-exec.jar pdf Docs/src/.*.md --mss Docs/docs.mss --resultFile Example.pdf`

There is no `--markdown` parameter! 

For all the options do:

    java -jar markdowndoc-cmd-line-2.2.0-exec.jar <generator> --help

Where \<genereator\> is pdf / html / markdown. You will **always** need `--resultFile <file>` !

----

About the warning for "An illegal reflective access operation has occured": This means that you are running a JDK 11 most probably, but you might get this in 10 also I think. From 12+ it will fail!

MarkdownDoc is written in Groovy 2.5 which produces JDK 5 compatible bytecode. In JDK 11 it still works, but you get the warning. If I fix this, then MarkdownDoc will not run on anything less than JDK 11 (maybe 10). I think a lot of people still is using JDK 8 due to the crazyness of 9+ (using modules requires **ALL** other dependencies to be modules also, that is 9+ and modularized!! Few of the thirdparty libraries used by many are modularized, sticking you between a rock and a hard place), and as of JDK 12 there is a guaranteed backwards incompatibility. You need 2 versions of code one for <9 and one for >=9. Java does not have a preprocessor so no \#ifdef ! You need to keep 2 different versions of the code. With GIT it would be possible to have <9 branches and >=9 branches, but it can get messy. 

Personally I'm a bit scared for the future of Java. In Sweden I have still not seen any company using anything higher than 8. There probably are, but the majority is still sticking to 8.

**Comment by tombensve** [comment]
Hmm ... very old. Closing this.
